INSERT INTO BOOK VALUES(1, 'War and peace');
INSERT INTO BOOK VALUES(2, 'Anna Karenina');
INSERT INTO BOOK VALUES(3, 'Shine');
INSERT INTO BOOK VALUES(4, 'Portrait of Dorian Grey');
INSERT INTO BOOK VALUES(5, 'Tales');
INSERT INTO BOOK VALUES(6, 'Design Patterns');

INSERT INTO AUTHOR(id, name) VALUES(1, 'Leon Tolstoy');
INSERT INTO AUTHOR(id, name) VALUES(2, 'Stephen King');
INSERT INTO AUTHOR(id, name) VALUES(3, 'Oscar Wilde');
INSERT INTO AUTHOR(id, name) VALUES(4, 'native');
INSERT INTO AUTHOR(id, name) VALUES(5, 'Erich Gamma');
INSERT INTO AUTHOR(id, name) VALUES(6, 'Richard Helm');
INSERT INTO AUTHOR(id, name) VALUES(7, 'Ralph Johnson');
INSERT INTO AUTHOR(id, name) VALUES(8, 'John Vlissides');

INSERT INTO AUTHOR_BOOK VALUES(1,1);
INSERT INTO AUTHOR_BOOK VALUES(1,2);
INSERT INTO AUTHOR_BOOK VALUES(2,3);
INSERT INTO AUTHOR_BOOK VALUES(3,4);
INSERT INTO AUTHOR_BOOK VALUES(4,5);
INSERT INTO AUTHOR_BOOK VALUES(5,6);
INSERT INTO AUTHOR_BOOK VALUES(6,6);
INSERT INTO AUTHOR_BOOK VALUES(7,6);
INSERT INTO AUTHOR_BOOK VALUES(8,6);






















